baseURL: https://blog.chezs.me/
languageCode: zh-cn
title: Che's Blog
theme: "PaperMod"
disqusShortname: "chezsblog"

params:
  defaultTheme: "dark"
  label:
    icon: "/images/logo.png"
  assets:
    favicon: "/images/favicon.ico"
  comments: true
  ShowCcLicense: true
  socialIcons:
    - name: "github"
      url: "https://github.com/superche"
  # profile-mode
  profileMode:
    enabled: true
    title: "Hi there \U0001F44B"
    subtitle: "### I'm CheZS.\n I work for Meituan as a software developer. You can follow me and I'm intrested in frontend technologies and fancy ideas. \n\n Thanks for my wife, who is a great mom and a good researcher. ğŸ¤± + ğŸ‘©â€ğŸ”¬"
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
